server:
  port: 8083
spring:
  application:
    name: ms-bank-transaction-service
 # config:
  #  import: optional:configserver:http://ms-bank-config-server:8888
  data: 
    mongodb:
     host: localhost
     port: 27017
     database: Bank 
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
client:
  msbankproduct:
    url: http://localhost:8080/product
  msbankaccount:
    :url: http://localhost:8081/account
    

kafka:
  topic:
    bank:
      transaction:
        bootcoin-create:
          name: bank-bootcoin-transaction-create
    bootcoin:
      transaction:
        update:
          name: bootcoin-transaction-update